@server = http://localhost:3000

### 유저 생성
POST {{server}}/users
Content-Type: application/json

{
  "email": "ttt123@naver.com",
  "password": "crud1234"
}

### 유저 업데이트
PATCH {{server}}/users/req-user
Content-Type: application/json

{
  "profile": {
    "nickname": "테스트1",
    "gender": false,
    "profileImg": "/abc.png"
  }
}

### 유저 로그인
POST {{server}}/auth
Content-Type: application/json

{
  "email": "abc1234@gmail.com",
  "password": "crud1234"
}


### 유저 로그인
POST {{server}}/auth
Content-Type: application/json

{
  "email": "ttt123@naver.com",
  "password": "crud1234"
}

### 유저 로그아웃
GET {{server}}/auth

### 로그인한 유저 정보 불러오기
GET {{server}}/users/req-user

### 관리자만 단일 유저정보 불러오기
GET {{server}}/users/c4df503f-85f9-498d-9a41-d6a772757dd2

### 관리자만 모든 유저정보 불러오기
GET {{server}}/users  

# ----------------------------------------------------

### 비밀번호 확인
POST {{server}}/users/password/check
Content-Type: application/json

{
  "password": "crud1234"
}

### 임시비밀번호 발급

### 비밀번호 수정
PATCH {{server}}/users/password/reset
Content-Type: application/json

{
  "password": "tls009988*"
}

# ----------------------------------------------------

### Job 카테고리 추가
POST {{server}}/categories/job
Content-Type: application/json

{
  "category": "DBA"
}

### DevCareer 카테고리 추가
POST {{server}}/categories/devCareer
Content-Type: application/json

{
  "category": "신입 (1년미만)"
}

### Job 카테고리 전체조회
GET {{server}}/categories/job

### DevCareer 카테고리 전체조회
GET {{server}}/categories/devCareer

### Job 카테고리 수정
PATCH {{server}}/categories/job/1
Content-Type: application/json

{
  "category": "백엔드"
}


### DevCareer 카테고리 수정
PATCH {{server}}/categories/devCareer/6
Content-Type: application/json

{
  "category": "신입 (1년미만)"
}

### Job 카테고리 삭제
DELETE {{server}}/categories/job/1

### DevCareer 카테고리 삭제
DELETE {{server}}/categories/devCareer/6

### Job 카테고리 복원 
GET {{server}}/categories/job/1/restore

### DevCareer 카테고리 복원 
GET {{server}}/categories/devCareer/6/restore

# ----------------------------------------------------

### TechStack 추가
POST {{server}}/tech-stacks
Content-Type: application/json

{
  "stackName": "Nest.js"
}

### TechStack 전체조회
GET {{server}}/tech-stacks

### TechStack 단일조회
GET {{server}}/tech-stacks/1

### TechStack 수정
PATCH {{server}}/tech-stacks/1
Content-Type: application/json

{
  "stackName": "타입스크립트"
}

### TechStack 삭제
DELETE {{server}}/tech-stacks/1

### TechStack 복원
GET {{server}}/tech-stacks/1/restore

# ----------------------------------------------------

### 스터디 생성
POST {{server}}/studies
Content-Type: application/json

{
  "name": "호호호호호호호",
  "content": "만관부만관부만관부만관부",
  "attendantsLimit": 3,
  "recruit": {
    "title": "키키키키키키",
    "recruitPlaceholder": "모집조건에 대해 적는 곳입니다."
  },
  "techStacks": [
    {
      "id": "1",
      "stackName": "타입스크립트"
    }
  ]
}

### 스터디 전체 조회
GET {{server}}/studies

### 스터디 조회 (offset)
GET {{server}}/studies/offset?limit=20&offset=0

### 스터디 조회 (offset + filter)
GET {{server}}/studies/offset?limit=20&offset=0&filter=1,2

### 스터디 단일 조회
GET {{server}}/studies/5

### 스터디 수정
PATCH {{server}}/studies/8
Content-Type: application/json

{
  "name": "미미미미미미초코오오오오",
  "content": "피피피피피피코코코노노노노노",
  "attendantsLimit": 5,
  "recruit": {
    "title": "ㅇ유유유융미미미",
    "recruitPlaceholder": "큐바바바바바큐큐"
  },
  "techStacks": [
    {
      "id": "2",
      "stackName": "typescript"
    },
    {
      "id": "1",
      "stackName": "javascript"
    }
  ]
}

### 스터디 삭제
DELETE {{server}}/studies/5

### 스터디 복원
GET {{server}}/studies/5/restore

### 스터디 북마크 
GET {{server}}/studies/5/bookmark

### 스터디 모집종료
GET {{server}}/studies/6/close

### 스터디 문의 생성
POST {{server}}/studies/7/inquiry
Content-Type: application/json

{
  "title": "이 스터디 뭐하는 스터디인가요?",
  "contents": "공지만 봐서는 도대체 뭘하는 스터디인지 잘 모르겠어서 문의드려요. 스터디 뭐하는 스터디인가요??"
}