@server = http://localhost:3000

### 유저 생성
POST {{server}}/users
Content-Type: application/json

{
  "email": "ttt123@naver.com",
  "password": "crud1234"
}

### 유저 업데이트
PATCH {{server}}/users/req-user
Content-Type: application/json

{
  "profile": {
    "nickname": "테스트1",
    "gender": false,
    "profileImg": "/abc.png"
  }
}

### 유저 로그인
POST {{server}}/auth
Content-Type: application/json

{
  "email": "ttt123@naver.com",
  "password": "crud1234"
}

### 유저 로그아웃
GET {{server}}/auth

### 로그인한 유저 정보 불러오기
GET {{server}}/users/req-user

### 관리자만 단일 유저정보 불러오기
GET {{server}}/users/c4df503f-85f9-498d-9a41-d6a772757dd2

### 관리자만 모든 유저정보 불러오기
GET {{server}}/users  

# ----------------------------------------------------

### 비밀번호 확인
POST {{server}}/users/password/check
Content-Type: application/json

{
  "password": "crud1234"
}

### 임시비밀번호 발급

### 비밀번호 수정
PATCH {{server}}/users/password/reset
Content-Type: application/json

{
  "password": "tls009988*"
}

# ----------------------------------------------------

### Job 카테고리 추가
POST {{server}}/categories/job
Content-Type: application/json

{
  "category": "DBA"
}

### DevCareer 카테고리 추가
POST {{server}}/categories/devCareer
Content-Type: application/json

{
  "category": "신입 (1년미만)"
}

### Job 카테고리 전체조회
GET {{server}}/categories/job

### DevCareer 카테고리 전체조회
GET {{server}}/categories/devCareer

### Job 카테고리 수정
PATCH {{server}}/categories/job/1
Content-Type: application/json

{
  "category": "백엔드"
}


### DevCareer 카테고리 수정
PATCH {{server}}/categories/devCareer/6
Content-Type: application/json

{
  "category": "신입 (1년미만)"
}

### Job 카테고리 삭제
DELETE {{server}}/categories/job/1

### DevCareer 카테고리 삭제
DELETE {{server}}/categories/devCareer/6

### Job 카테고리 복원 
GET {{server}}/categories/job/1/restore

### DevCareer 카테고리 복원 
GET {{server}}/categories/devCareer/6/restore

# ----------------------------------------------------

### TechStack 추가
POST {{server}}/tech-stacks
Content-Type: application/json

{
  "stackName": "Nest.js"
}

### TechStack 전체조회
GET {{server}}/tech-stacks

### TechStack 단일조회
GET {{server}}/tech-stacks/1

### TechStack 수정
PATCH {{server}}/tech-stacks/1
Content-Type: application/json

{
  "stackName": "타입스크립트"
}

### TechStack 삭제
DELETE {{server}}/tech-stacks/1

### TechStack 복원
GET {{server}}/tech-stacks/1/restore

# ----------------------------------------------------

### 스터디 생성
POST {{server}}/studies
Content-Type: application/json

{
  "name": "맨날쉬고싶다",
  "content": " 스터디 생성 테스트입니다. 많은 관심부탁드려요~",
  "attendantsLimit": 5,
  "recruit": {
    "title": "1스터디 모집",
    "recruitPlaceholder": "모집조건에 대해 적는 곳입니다."
  },
  "techStacks": [
    {
      "id": "1",
      "stackName": "타입스크립트"
    },
    {
      "id": "2",
      "stackName": "자바스크립트"
    },
    {
      "id": "3",
      "stackName": "nest.js"
    }
  ]
}

### 스터디 전체 조회
GET {{server}}/studies

### 스터디 단일 조회
GET {{server}}/studies/4

### 스터디 수정
PATCH {{server}}/studies/4
Content-Type: application/json

{
  "name": "tttttttttt",
  "content": " aaaaaaaa 수정 테스트입니다. 잘되나?",
  "attendantsLimit": 2,
  "recruit": {
    "title": "gdasg 모집",
    "recruitPlaceholder": "aaaaa모집조건이 매우 까다로움"
  },
  "techStacks": [
    {
      "id": "2",
      "stackName": "자바스크립트"
    },
    {
      "id": "3",
      "stackName": "nest.js"
    }
  ]
}